### ISSUE TITLE
Check for system functions

### ISSUE THREAD

**Issue by peter-mw** [drewm/morse#13]
Hello,

I would like to have functionality to check for some system functions availability

The functions i want to check are

`ini_set`
`set_time_limit`
`exec`
`shell_exec`
`ignore_user_abort`
`passthru`
`system`
`popen`
`proc_open `

On some hosts those functions are disabled with the `disable_functions` setting in php.ini

Maybe the system functions deserve a namespace like system/ini_set , etc

Currently i am using very simple way to check but i would like to see support for those functions in the morse-php library, so i can include it in my project

```php
// example way to check


$disabled = ini_get('disable_functions');

if (!strstr($disabled, 'ini_set')){
ini_set('memory_limit', '512M');
}


if (!strstr($disabled, 'set_time_limit')) {
set_time_limit(600);
}


if (!strstr($disabled, 'ignore_user_abort')) {
ignore_user_abort();
}

**Comment by drewm** [comment]
This sounds like a good addition.

**Comment by nlzet** [comment]
I guess this is already resolved by https://github.com/drewm/morse/commit/f198154a88dbcf601d33e5ecc78cbdacf6404937

**Comment by drewm** [comment]
Only 7 minutes ago - give me a chance! Fixed in https://github.com/drewm/morse/commit/88d6e1217f8b424e384354d270f8501e3e8bb165

**Comment by nlzet** [comment]
Oops, didn't look at the date sorry

**Comment by peter-mw** [comment]
Nice! Thanks for the addition

I am going to use this now  :)
